export const LOGIN_USER = "LOGIN_USER"
export const SELECTED_PRODUCT = "SELECTED_PRODUCT"
export const ALL_PRODUCTS = "ALL_PRODUCTS"
export const CART = "CART"
export const FSS = "FSS"
export const ORDER = "ORDER"
export const GET_ORDERS = "GET_ORDERS"
export const GET_USERS = "GET_USERS"
export const GET_DISPLAY = "GET_DISPLAY"
export const GET_FRAME = "GET_FRAME"
export const GET_SIZE = "GET_SIZE"
export const GET_STYLE = "GET_STYLE"

export const ORDER_IN_PROCESS="ORDER_IN_PROCESS"
export const ID_FOR_ORDERS= "ID_FOR_ORDERS"
export const DATA_PRODUCT= "DATA_PRODUCT"
export const SELECT_STYLE='SELECT_STYLE'
export const ALL_FSS="ALL_FSS"
export const DATA_PRODUCTS ="DATA_PRODUCTS"

